export const C = {
  green: "#16a34a",
  green2: "#dcfce7",
  blue: "#2563eb",
  blue2: "#dbeafe",
  red: "#dc2626",
  red2: "#fee2e2",
  gray: "#6b7280",
  bg: "#f0fdf4",
  white: "#ffffff",
  border: "#e5e7eb",
  text: "#111827",
};

export const s = {
  page: {
    minHeight: "100vh",
    background: C.bg,
    fontFamily: "'Inter', sans-serif",
    color: C.text,
  },
  nav: {
    background: C.green,
    padding: "14px 28px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    boxShadow: "0 2px 12px rgba(0,0,0,0.12)",
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  card: {
    background: "#ffffff",
    borderRadius: "16px",
    padding: "24px",
    boxShadow: "0 2px 16px rgba(0,0,0,0.07)",
    marginBottom: "20px",
    border: "1px solid #e5e7eb",
  },
  input: {
    display: "block",
    width: "100%",
    padding: "10px 14px",
    marginBottom: "12px",
    border: "1.5px solid #e5e7eb",
    borderRadius: "10px",
    fontSize: "14px",
    fontFamily: "'Inter', sans-serif",
    outline: "none",
    background: "#f9fafb",
    boxSizing: "border-box",
  },
  btn: (bg, color = "#fff") => ({
    padding: "10px 22px",
    background: bg,
    color,
    border: "none",
    borderRadius: "10px",
    fontWeight: "600",
    fontSize: "14px",
    cursor: "pointer",
    fontFamily: "'Inter', sans-serif",
    transition: "opacity .2s, transform .15s",
    marginRight: "8px",
    marginBottom: "8px",
  }),
  badge: (bg, color) => ({
    display: "inline-block",
    padding: "3px 12px",
    borderRadius: "20px",
    fontSize: "12px",
    fontWeight: "600",
    background: bg,
    color,
  }),
};
